import { CountyDescriptionsType } from "../types/types"

export const CountyDescriptions: CountyDescriptionsType = {
    Kern: ["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi","Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi"],
    SanLuis: ["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi","Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi"],
    SanBar: ["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi","Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi"],
    Ven: ["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi","Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi"],
    LosAng: ["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi","Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi"],
    SanBern: ["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi","Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi"],
    River: ["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi","Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi"],
    Orange: ["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi","Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi"],
    Imperial: ["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi","Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi"],
    SanDiego: ["Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi","Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero temporibus vel hic quia quidem nostrum expedita perferendis voluptatem esse sunt ipsum ad sit voluptatum, doloribus beatae maiores molestias consequatur modi"],
}