import { LocationNamesType } from "../types/types";

export const LocationNames: LocationNamesType = {
  Kern: ["Lake Isabella", "Lava Tube Trail", "Silver City Ghost Town"],
  SanLuis: [
    "Dorn Pyramid",
    "Hearst Castle",
    "Madonna Inn",
    "Chamisal Vineyards",
  ],
  SanBar: [
    "Montecito Hot Springs",
    "Solvang",
    "Sacred Space",
    "Santa Barbara Museum of Art",
    "Stearns Wharf",
    "Channel Islands National Park",
  ],
  Ven: ["Mullin Automotive Museum", "Paradise Falls", "Gardens of the World"],
  LosAng: [
    "Venice Canals",
    "Malibu Hindu Temple",
    "Greystone Mansion",
    "Getty Villa",
    "Witch House",
    "SRFL Shrine",
    "Descanso Gardens",
  ],
  SanBern: [
    "BAPS Shri Swaminarayan Mandir",
    " Mozumdar Temple",
    "Egyptian Building",
    "Joshua Tree National Park",
    "Deep Creek Hot Springs",
    "Big Bear Lake",
  ],
  River: [
    "Mount Rubidoux",
    "Cabot Pueblo Museum",
    "Mission Inn Museum",
    "Lake Fulmor",
  ],
  Orange: [
    "Pirate Tower",
    "Anaheim Packing District",
    "Noguchi Gardens",
    "Disneyland",
    "Newport Beach",
    "Marconi Automotive Museum",
    "Knott's Berry Farm",
  ],
  Imperial: ["Bombay Beach Ruins", "Salvation Mountain", "Salton Sea"],
  SanDiego: [
    "Balboa Park",
    "Harper's Topiary Garden",
    "Heritage Park",
    "Scripps Coastal Meander",
    "USS Midway Museum",
    "San Diego Zoo",
    "Legoland",
    "Old Town",
    "La Jolla Cove",
    "Liberty Station Park",
    "Seaport Village",
    "Marconi Automotive Museum",
  ],
};
